version: '3'

services:
  nginx:
    build: ./nginx
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '80:80'
    depends_on:
      - web
    volumes:
      - static_data:/var/www/static
  web:
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    ports:
      - '8080:8000'
    volumes:
      - ./mysite:/code
      - /code/node_modules
      - static_data:/code/static_root

volumes:
  static_data:
